apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-application-deployment
  namespace: metallb-system
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    helm:
      releaseName: metallb-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
    targetRevision: "0.13.10"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  # This is a workaround for mutated CRD, where ingoreDifferences must be set
  # https://github.com/metallb/metallb/issues/1681
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle