apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-application-deployment
  namespace: metallb-system
spec:
  project: default
  source:
    chart: metallb/metallb
    repoURL: https://metallb.github.io/metallb
    helm:
      releaseName: metallb-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
