apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-cluster
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: '*'
    helm:
      releaseName: vm-cluster
      # "FATAL: cannot create lock file: cannot acquire lock on file \"/storage/flock.lock\": resource temporarily unavailable; make sure a single process has exclusive access to \"/storage\"
      # Had to set the replicas of vmstorage to 1 because of this error
      values: |
        vminsert:
          persistentVolume:
            enabled: true
            existingClaim: vminsert-pvc
          service:
            type: LoadBalancer
        vmstorage:
          persistentVolume:
            enabled: true
            existingClaim: vmstorage-pvc
          service:
            type: LoadBalancer
          replicas: 1
        vmselect:
          service:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 