apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-cluster
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: '*'
    helm:
      releaseName: vm-cluster
      values: |
        vminsert:
          persistentVolume:
            enabled: true
            existingClaim: vminsert-main-pvc
          service:
            type: LoadBalancer
        vmstorage:
          persistentVolume:
            enabled: true
            existingClaim: vmstorage-main-pvc
          service:
            type: LoadBalancer
        vmselect:
          service:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 