---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vminsert-pvc
  namespace: victoriametrics
spec:
  storageClassName: "main-nfs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # NFS Subdir Provisioner doesn't care at all abou this
      storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmstorage-pvc
  namespace: victoriametrics
spec:
  storageClassName: "main-nfs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # NFS Subdir Provisioner doesn't care at all abou this
      storage: 100M