---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vminsert-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  # https://stackoverflow.com/questions/34282704/can-a-pvc-be-bound-to-a-specific-pv
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: victoriametrics
    name: vminsert-pvc
  nfs:
    server: "192.168.2.155"
    path: "/mnt/main_pool/kube_docker_volumes/victoriametrics/vminsert"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vminsert-pvc
  namespace: victoriametrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # NFS Subdir Provisioner doesn't care at all abou this
      storage: 100M
