source:
  helm:
    values: |
      nfs:
        server: "192.168.2.155"
        path: "/mnt/main_pool/kube_docker_volumes"
      storageClass:
        name: "main-nfs-sc"
        provisionerName: "k8s-sigs.io/main-nfs-subdir-external-provisioner"
        defaultClass: true
        accessModes: 
        - "ReadWriteOnce"
        - "ReadWriteMany"