apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: '*'
    helm:
      releaseName: vm-stack
      valuesObject:
        grafana:
          enabled: true
        vmstorage:
          persistentVolume:
            enabled: true
            existingClaim: vmstorage-main-pvc
        vmselect:
          persistentVolume:
            enabled: true
            existingClaim: vmselect-main-pvc
        service:
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 