apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
  labels:
    name: main-cluster
    usecase: database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-6
  monitoring:
    enablePodMonitor: true

  storage:
    size: 30Gi
    storageClass: local-path