apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
  labels:
    name: main-cluster
    usecase: database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 30Gi
    storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: main-cluster-cnpg-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.11.0.5
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: main-cluster
    role: primary