apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
  labels:
    name: test-cluster
    usecase: database
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: test-cluster-cnpg-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.11.0.6
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: test-cluster
    role: primary