apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.2
    helm:
      releaseName: nfs-subdir-external-provisioner-release
      values: |
        nfs:
          server: "192.168.2.155"
          path: "/mnt/main_pool/kube_docker_volumes"
        storageClass:
          name: "main-nfs-sc"
          provisionerName: "k8s-sigs.io/main-nfs-subdir-external-provisioner"
          defaultClass: true
          accessModes: 
          - "ReadWriteOnce"
          - "ReadWriteMany"
          onDelete: "Retain"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-subdir-external-provisioner
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 