apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium-grimmie
spec:
  selector:
    matchLabels:
      app: trilium-grimmie
  replicas: 1
  template:
    metadata:
      labels:
        app: trilium-grimmie
    spec:
      containers:
      - name: trilium-grimmie
        image: zadam/trilium:0.60.4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: trilium-grimmie-pvc
          mountPath: /home/node
      volumes:
      - name: trilium-grimmie-pvc
        persistentVolumeClaim:
          claimName: trilium-grimmie-pvc