apiVersion: v1
kind: Service
metadata:
  name: trilium-grimmie-lb
spec:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.11.0.13
  selector:
    app: trilium-grimmie
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
