apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-agent
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-cluster
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: '*'
    helm:
      releaseName: vm-agent-release
      values: |
        service:
          main:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 