apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-agent
  namespace: argocd
spec:
  project: default
  source:
    chart: victoria-metrics-cluster
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: '*'
    helm:
      releaseName: vm-agent-release
      values: |
        service:
          type: LoadBalancer
        config:
          global:
            scrape_timeout: 30m

          scrape_configs:
            - job_name: 'idrac-exporter-metz'
              metrics_path: '/metrics?target=idrac-metz.fuller.network'
              scrape_timeout: 600s
              scrape_interval: 30m
              static_configs:
                - targets: ['idrac_exporter:9348']
            - job_name: 'idrac-exporter-therazane'
              metrics_path: 'metrics?target=idrac-therazane.fuller.network'
              scrape_timeout: 600s
              scrape_interval: 30m
              static_configs:
                - targets: ['idrac_exporter:9348']
            - job_name: 'pfsense-node'
              scrape_timeout: 120s
              scrape_interval: 4m
              metrics_path: '/metrics'
              static_configs:
                - targets: ['192.168.1.1:9100']
            - job_name: 'unifi-metrics'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['logmon.fuller.network:9130']
            - job_name: 'truenas-graphite'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['logmon.fuller.network:9108']
            - job_name: 'nextcloud-exporter'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['nextcloud-exporter:9205']
            - job_name: 'uptime-kuma-stats'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['logmon.fuller.network:3001']
              basic_auth:
                username: perf3ct
                password: "0796INsane!224"
            - job_name: "mikrotik-snmp-job"
              static_configs:
                - targets:
                    - hydra.fuller.network # SNMP device.
                    - idrac-metz.fuller.network
                    - idrac-therazane.fuller.network
              metrics_path: /snmp
              params:
                module: [if_mib]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: snmp-exporter:9116 # The SNMP exporter's real hostname:port.
            - job_name: 'homelab-node-exporter'
              metrics_path: '/metrics'
              static_configs:
                - targets: ["fullernas.fuller.network:9100", "ubuntuserver.fuller.network:9100", "triss.fuller.network:9100", "gitea.fuller.network:9100", "nginxserver.fuller.network:9100", "crackedgitlab.fuller.network:9100", "personalbookstack.fuller.network:9100", "wiki.fuller.network:9100", "mainpostgres.fuller.network:9100", "pterodactyl.fuller.network:9100", "kubemasternode1.fuller.network:9100", "kubemasternode2.fuller.network:9100", "kubehost1.fuller.network:9100", "kubehost2.fuller.network:9100", "newmatrix.fuller.network:9100", "fancynextcloud.fuller.network:9100", "logmon.fuller.network:9100", "homelabmonitor.fuller.network:9100", "vpnserver-wg.fuller.network:9100", "vpnserver-openvpn.fuller.network:9100", "newmasternode1.fuller.network:9100", "newworkernode1.fuller.network:9100", "newworkernode2.fuller.network:9100"]

  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 