apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-provisioner-system
  project: default
  source:
    path: kubernetes/system/local-path-provisioner
    repoURL: https://gitea.perfectra1n.com/perf3ct/homelab-ops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 