apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudnative-pg
  project: default
  source:
    path: kubernetes/apps/cloudnative-pg
    repoURL: https://gitea.perfectra1n.com/perf3ct/homelab-ops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 